#pragma once

#define SWAP_CHAIN_BUFFER_COUNT 3
#define BACK_BUFFER_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM // DXGI_FORMAT_R8G8B8A8_UNORM = 28

typedef enum ComponentTypes
{
	TRANSFORM = 0,
	MESH_REFERENCE,
	SHADER_REFERENCE,
	COMPONENT_TYPES_COUNT	
} ComponentType;